site_name: Hotel Documentation
nav:
  - Home: endpoints.md
  - Models: models.md
  
  - '1.1 Containerization': 1.1_containerization.md
  - '1.2 Orchestration': 1.2_orchestration.md
  - '2.1.1 Manual filters': 2.1.1_manual_filters.md
  - '2.1.2 Auto filters': 2.1.2_auto_filters.md
  - '2.2.1 Default Pagination': 2.2.1_default_pagination.md
  - '2.2.2 Custom pagination': 2.2.2_custom_pagination.md
  - '2.3.1 File upload & validation': 2.3.1_file_upload.md
  - '2.4.1 Signals': 2.4.1_signals.md
  - '3.1.1 Tests': 3.1.1_tests.md
  - '4.1.1 Filters interface': 4.1.1_filters_interface.md

theme:
  name: material
  palette:
    scheme: slate
    accent: light blue
    primary: blue
